complete -c note -x -a edit -d 'edit the note identified by the path'
complete -c note -x -a find -d 'find the note by searching file names'
complete -c note -x -a search -d 'perform a full text search for patterns'
complete -c note -x -a create -d 'create a new note'
complete -c note -x -a pcreate -d 'create a new note within a project area'
complete -c note -x -a move -d 'explain,,,'
complete -c note -x -a sync -d 'synchronise notes with origin git repo'
complete -c note -x -a home -d 'cd to the notes directory'
complete -c note -x -a help -d 'display commands and options'
